ALTER TABLE COMMENTS
    ADD COLUMN AREA VARCHAR(100) AFTER IP
ALTER TABLE VISIT
    ADD COLUMN AREA VARCHAR(100) AFTER IP


CREATE TABLE WORKER_NODE
(
    ID          BIGINT      NOT NULL AUTO_INCREMENT COMMENT 'auto increment id',
    HOST_NAME   VARCHAR(64) NOT NULL COMMENT 'host name',
    PORT        VARCHAR(64) NOT NULL COMMENT 'port',
    TYPE        INT         NOT NULL COMMENT 'node type: ACTUAL or CONTAINER',
    LAUNCH_DATE DATE        NOT NULL COMMENT 'launch date',
    MODIFIED    TIMESTAMP   NOT NULL COMMENT 'modified time',
    CREATED     TIMESTAMP   NOT NULL COMMENT 'created time',
    PRIMARY KEY (ID)
)
    COMMENT ='DB WorkerID Assigner for UID Generator', ENGINE = INNODB;



INSERT
INTO
    WEBCONF
VALUES
    (13, 'IS_LOGIN_NEED_CAPTCHA', NULL, NULL, 1, '2020-11-20 10:39:54', '2021-01-26 10:02:07')

