ALTER TABLE COMMENTS
    ADD COLUMN AREA VARCHAR(100) AFTER IP
ALTER TABLE VISIT
    ADD COLUMN AREA VARCHAR(100) AFTER IP


CREATE TABLE WORKER_NODE
(
    ID          BIGINT      NOT NULL AUTO_INCREMENT COMMENT 'auto increment id',
    HOST_NAME   VARCHAR(64) NOT NULL COMMENT 'host name',
    PORT        VARCHAR(64) NOT NULL COMMENT 'port',
    TYPE        INT         NOT NULL COMMENT 'node type: ACTUAL or CONTAINER',
    LAUNCH_DATE DATE        NOT NULL COMMENT 'launch date',
    MODIFIED    TIMESTAMP   NOT NULL COMMENT 'modified time',
    CREATED     TIMESTAMP   NOT NULL COMMENT 'created time',
    PRIMARY KEY (ID)
)
    COMMENT ='DB WorkerID Assigner for UID Generator', ENGINE = INNODB;



INSERT
INTO
    WEBCONF
VALUES
    (13, 'IS_LOGIN_NEED_CAPTCHA', NULL, NULL, 1, '2020-11-20 10:39:54', '2021-01-26 10:02:07');


ALTER TABLE ADMIN
    ADD COLUMN NICK VARCHAR(20) AFTER PASSWORD;
ALTER TABLE MENU
    ADD COLUMN VALID CHAR(1) DEFAULT '1' AFTER URL;
ALTER TABLE MENU
    MODIFY COLUMN ICON VARCHAR(50);


-- update menu
UPDATE `menu`
SET
    `OID`='8',
    `NAME`='index',
    `INDEX`='0',
    `CREATE_DATE`='2020-08-15 22:37:17',
    `UPDATE_DATE`='2020-08-15 22:37:17',
    `TYPE`='2',
    `ICON`='layui-icon-home',
    `TEXT`='首页',
    `URL`=NULL,
    `VALID`='1',
    `PARENT_OID`='0'
WHERE
    (`OID` = '8');
UPDATE `menu`
SET
    `OID`='9',
    `NAME`='index',
    `INDEX`='0',
    `CREATE_DATE`='2020-08-15 22:37:17',
    `UPDATE_DATE`='2020-08-15 22:37:17',
    `TYPE`='2',
    `ICON`=NULL,
    `TEXT`='主页',
    `URL`='index',
    `VALID`='1',
    `PARENT_OID`='8'
WHERE
    (`OID` = '9');
UPDATE `menu`
SET
    `OID`='10',
    `NAME`='dynamic',
    `INDEX`='0',
    `CREATE_DATE`='2020-08-15 22:37:17',
    `UPDATE_DATE`='2020-08-15 22:37:17',
    `TYPE`='2',
    `ICON`=NULL,
    `TEXT`='动态',
    `URL`='/dynamic',
    `VALID`='1',
    `PARENT_OID`='8'
WHERE
    (`OID` = '10');
UPDATE `menu`
SET
    `OID`='11',
    `NAME`='articleMangement',
    `INDEX`='0',
    `CREATE_DATE`='2020-08-15 22:37:17',
    `UPDATE_DATE`='2020-08-15 22:37:17',
    `TYPE`='2',
    `ICON`='layui-icon-template-1',
    `TEXT`='文章管理',
    `URL`=NULL,
    `VALID`='1',
    `PARENT_OID`='0'
WHERE
    (`OID` = '11');
UPDATE `menu`
SET
    `OID`='12',
    `NAME`='articlePublished',
    `INDEX`='0',
    `CREATE_DATE`='2020-08-15 22:37:17',
    `UPDATE_DATE`='2020-08-15 22:37:17',
    `TYPE`='2',
    `ICON`=NULL,
    `TEXT`='文章发布',
    `URL`='/article/published',
    `VALID`='1',
    `PARENT_OID`='11'
WHERE
    (`OID` = '12');
UPDATE `menu`
SET
    `OID`='13',
    `NAME`='myArticle',
    `INDEX`='0',
    `CREATE_DATE`='2020-08-15 22:37:17',
    `UPDATE_DATE`='2020-08-15 22:37:17',
    `TYPE`='2',
    `ICON`=NULL,
    `TEXT`='我的文章',
    `URL`='/article/list',
    `VALID`='1',
    `PARENT_OID`='11'
WHERE
    (`OID` = '13');
UPDATE `menu`
SET
    `OID`='14',
    `NAME`='commentManagement',
    `INDEX`='0',
    `CREATE_DATE`='2020-08-15 22:37:17',
    `UPDATE_DATE`='2020-08-15 22:37:17',
    `TYPE`='2',
    `ICON`=NULL,
    `TEXT`='评论管理',
    `URL`='/comment/list',
    `VALID`='1',
    `PARENT_OID`='11'
WHERE
    (`OID` = '14');
UPDATE `menu`
SET
    `OID`='15',
    `NAME`='articleTags',
    `INDEX`='0',
    `CREATE_DATE`='2020-08-15 22:37:17',
    `UPDATE_DATE`='2020-08-15 22:37:17',
    `TYPE`='2',
    `ICON`=NULL,
    `TEXT`='文章标签',
    `URL`='/article/tags',
    `VALID`='1',
    `PARENT_OID`='11'
WHERE
    (`OID` = '15');
UPDATE `menu`
SET
    `OID`='16',
    `NAME`='recycleBin',
    `INDEX`='0',
    `CREATE_DATE`='2020-08-15 22:37:17',
    `UPDATE_DATE`='2020-08-15 22:37:17',
    `TYPE`='2',
    `ICON`=NULL,
    `TEXT`='文章回收站',
    `URL`='/article/recycleBin',
    `VALID`='1',
    `PARENT_OID`='11'
WHERE
    (`OID` = '16');
UPDATE `menu`
SET
    `OID`='17',
    `NAME`='menuManagement',
    `INDEX`='0',
    `CREATE_DATE`='2020-08-15 22:37:17',
    `UPDATE_DATE`='2020-08-15 22:37:17',
    `TYPE`='2',
    `ICON`='layui-icon-menu-fill',
    `TEXT`='菜单管理',
    `URL`=NULL,
    `VALID`='1',
    `PARENT_OID`='0'
WHERE
    (`OID` = '17');
UPDATE `menu`
SET
    `OID`='18',
    `NAME`='menuMg',
    `INDEX`='0',
    `CREATE_DATE`='2020-08-15 22:37:17',
    `UPDATE_DATE`='2020-08-15 22:37:17',
    `TYPE`='2',
    `ICON`=NULL,
    `TEXT`='菜单管理',
    `URL`='/menu/view',
    `VALID`='1',
    `PARENT_OID`='17'
WHERE
    (`OID` = '18');
UPDATE `menu`
SET
    `OID`='19',
    `NAME`='userManagement',
    `INDEX`='0',
    `CREATE_DATE`='2020-08-15 22:37:17',
    `UPDATE_DATE`='2020-08-15 22:37:17',
    `TYPE`='2',
    `ICON`=NULL,
    `TEXT`='用户管理',
    `URL`=NULL,
    `VALID`='0',
    `PARENT_OID`='0'
WHERE
    (`OID` = '19');
UPDATE `menu`
SET
    `OID`='20',
    `NAME`='regUser',
    `INDEX`='0',
    `CREATE_DATE`='2020-08-15 22:37:17',
    `UPDATE_DATE`='2020-08-15 22:37:17',
    `TYPE`='2',
    `ICON`=NULL,
    `TEXT`='注册用户',
    `URL`=NULL,
    `VALID`='0',
    `PARENT_OID`='19'
WHERE
    (`OID` = '20');
UPDATE `menu`
SET
    `OID`='21',
    `NAME`='systemManagement',
    `INDEX`='0',
    `CREATE_DATE`='2020-08-15 22:37:17',
    `UPDATE_DATE`='2020-08-15 22:37:17',
    `TYPE`='2',
    `ICON`='layui-icon-set-fill',
    `TEXT`='系统管理',
    `URL`=NULL,
    `VALID`='1',
    `PARENT_OID`='0'
WHERE
    (`OID` = '21');
UPDATE `menu`
SET
    `OID`='22',
    `NAME`='webConfig',
    `INDEX`='0',
    `CREATE_DATE`='2020-08-15 22:37:17',
    `UPDATE_DATE`='2020-08-15 22:37:17',
    `TYPE`='2',
    `ICON`=NULL,
    `TEXT`='网站配置',
    `URL`='/web/config',
    `VALID`='1',
    `PARENT_OID`='21'
WHERE
    (`OID` = '22');
UPDATE `menu`
SET
    `OID`='23',
    `NAME`='pptManagement',
    `INDEX`='0',
    `CREATE_DATE`='2020-08-15 22:37:17',
    `UPDATE_DATE`='2020-08-15 22:37:17',
    `TYPE`='2',
    `ICON`=NULL,
    `TEXT`='首页幻灯片',
    `URL`='/web/ppt',
    `VALID`='0',
    `PARENT_OID`='21'
WHERE
    (`OID` = '23');
UPDATE `menu`
SET
    `OID`='24',
    `NAME`='clearCache',
    `INDEX`='0',
    `CREATE_DATE`='2020-08-15 22:37:17',
    `UPDATE_DATE`='2020-08-15 22:37:17',
    `TYPE`='2',
    `ICON`=NULL,
    `TEXT`='清除缓存',
    `URL`='/web/clear',
    `VALID`='1',
    `PARENT_OID`='21'
WHERE
    (`OID` = '24');



ALTER TABLE FILE_UPLOAD ADD COLUMN MEDIA_INFO VARCHAR(1000) AFTER TYPE;
ALTER TABLE FILE_UPLOAD DROP COLUMN MEDIA_TIME ;


ALTER TABLE WEBCONF ADD COLUMN VALID CHAR(1) AFTER BOOLEAN_VALUE DEFAULT '1';
ALTER TABLE WEBCONF ADD COLUMN `DESC` VARCHAR(200) AFTER `KEY`;
ALTER TABLE WEBCONF ADD COLUMN TITLE VARCHAR(50) AFTER `DESC`;
ALTER TABLE WEBCONF ADD COLUMN VALUE_TYPE VARCHAR(10) AFTER TITLE COMMENT 'S:STRING, N:NUMBER; D:DATE; B:BOOLEAN, default:S';
ALTER TABLE WEBCONF ADD COLUMN FORM_TYPE VARCHAR(20) AFTER TYPE COMMENT 'INPUT_TEXT, TEXTAREA; INPUT_FILE_IMAGE; INPUT_TEXT_NUMBER,INPUT_CHECKBOX:,SELECT,RADIO, default:INPUT_TEXT';
ALTER TABLE WEBCONF ADD COLUMN DATE_VALUE datetime AFTER BOOLEAN_VALUE;
ALTER TABLE WEBCONF ADD COLUMN MANDATORY CHAR(1) AFTER DATE_VALUE COMMENT '是否必填';
ALTER TABLE WEBCONF ADD COLUMN VALIDATE_TYPE VARCHAR(200) AFTER MANDATORY COMMENT "maxLength|number|minNum|maxNum|regex... '|'分隔";
ALTER TABLE WEBCONF ADD COLUMN VALIDATE_VALUE VARCHAR(1000) AFTER VALIDATE_TYPE COMMENT "JSON数据 eg: {\"maxLength\":{\"value\":50,\"lay-verify\":\"lay-max=''50''\"}}";
ALTER TABLE WEBCONF ADD COLUMN `INDEX` int(6) AFTER VALIDATE_VALUE  DEFAULT 1;
ALTER TABLE WEBCONF MODIFY COLUMN `NUM_VALUE` DECIMAL(10,4)  ;
ALTER TABLE WEBCONF MODIFY COLUMN `STRING_VALUE` VARCHAR(2000)  ;
ALTER TABLE ARTICLE MODIFY COLUMN `STATUS` int(11) NOT NULL COMMENT '文章状态 1已发布  0草稿    -1回收站  -2 临时文章';


CREATE TABLE `TEMP_ARTICLE` (
                                `OID` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '表自增唯一id',
                                `AUTHOR` varchar(500) DEFAULT NULL COMMENT '文章作者',
                                `TITLE` text NULL COMMENT '文章标题',
                                `CONTENT` longtext NULL COMMENT '文章内容(html格式)',
                                `TYPE_ID` int(11) DEFAULT '0' COMMENT '文章类型',
                                `IS_COMMENT` int(11) DEFAULT NULL COMMENT '是否可以被评论',
                                `IMG_SRC` varchar(1024) DEFAULT NULL COMMENT '文章缩略图',
                                `VISIT_TYPE` int(11) DEFAULT '1' COMMENT '公开度 -1：密码  , 1：公开 ,私密:0 ,置顶:2',
                                `PASSWORD` varchar(500) DEFAULT NULL COMMENT '当公开度为-1时设置',
                                `OLD_OID` bigint(20) unsigned DEFAULT NULL COMMENT '当文章是已有文章时,文章的OID,当是新文章时为-1',
                                `TAGS` varchar(2000) DEFAULT NULL COMMENT '文章标签的JSON数组',
                                `PAGE` int(2) NOT NULL COMMENT '1:发布页面 2编辑页面',
                                `STATUS` int(11) NOT NULL COMMENT '临时文章状态 1已经恢复  0临时缓存状态  -1作废',
                                `RESTORE_OID` bigint(20) unsigned DEFAULT NULL COMMENT '恢复文章的OID',
                                `CREATE_DATE` datetime NOT NULL,
                                `UPDATE_DATE` datetime NOT NULL,
                                PRIMARY KEY (`OID`)
) ENGINE = InnoDB
  AUTO_INCREMENT = 1
  DEFAULT CHARSET = utf8 COMMENT ='临时文章表';


ALTER TABLE MENU
    MODIFY COLUMN `CREATE_DATE` datetime NOT NULL AFTER PARENT_OID;
ALTER TABLE MENU
    MODIFY COLUMN `UPDATE_DATE` datetime NOT NULL AFTER CREATE_DATE;



ALTER TABLE WEBCONF
    ADD COLUMN `TAB_TYPE` VARCHAR(20) AFTER `FORM_TYPE`;
ALTER TABLE WEBCONF
    ADD COLUMN `TAB_TYPE_DESC` VARCHAR(50) AFTER `TAB_TYPE`;


UPDATE `webconf`
SET
    `TAB_TYPE`='SYS',
    `TAB_TYPE_DESC`='系统配置'
WHERE
    (`OID` IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13));



INSERT
INTO
    `webconf`
    (`OID`, `KEY`, `DESC`, `TITLE`, `VALUE_TYPE`, `FORM_TYPE`, `TAB_TYPE`, `TAB_TYPE_DESC`, `STRING_VALUE`, `NUM_VALUE`,
     `BOOLEAN_VALUE`, `DATE_VALUE`, `MANDATORY`, `VALIDATE_TYPE`, `VALIDATE_VALUE`, `INDEX`, `VALID`, `CREATE_DATE`,
     `UPDATE_DATE`)
VALUES
    ('15', 'EMAIL_HOST', '邮件服务器的SMTP地址', '邮件SMTP地址',
     'S', 'INPUT_TEXT', 'EMAIL', '邮件配置',
     '', NULL, NULL, NULL, NULL, NULL, NULL, '13', '1', '2020-11-20 10:39:54', '2021-07-01 15:57:11');
INSERT
INTO
    `webconf`
    (`OID`, `KEY`, `DESC`, `TITLE`, `VALUE_TYPE`, `FORM_TYPE`, `TAB_TYPE`, `TAB_TYPE_DESC`, `STRING_VALUE`, `NUM_VALUE`,
     `BOOLEAN_VALUE`, `DATE_VALUE`, `MANDATORY`, `VALIDATE_TYPE`, `VALIDATE_VALUE`, `INDEX`, `VALID`, `CREATE_DATE`,
     `UPDATE_DATE`)
VALUES
    ('16', 'EMAIL_PORT', '邮件服务器的SMTP端口', '邮件SMTP端口',
     'S', 'INPUT_TEXT', 'EMAIL', '邮件配置',
     '', NULL, NULL, NULL, NULL, NULL, NULL, '13', '1', '2020-11-20 10:39:54', '2021-07-01 15:57:11');
INSERT
INTO
    `webconf`
    (`OID`, `KEY`, `DESC`, `TITLE`, `VALUE_TYPE`, `FORM_TYPE`, `TAB_TYPE`, `TAB_TYPE_DESC`, `STRING_VALUE`, `NUM_VALUE`,
     `BOOLEAN_VALUE`, `DATE_VALUE`, `MANDATORY`, `VALIDATE_TYPE`, `VALIDATE_VALUE`, `INDEX`, `VALID`, `CREATE_DATE`,
     `UPDATE_DATE`)
VALUES
    ('17', 'EMAIL_USER', '发件人（必须正确，否则发送失败）', '用户',
     'S', 'INPUT_TEXT', 'EMAIL', '邮件配置',
     '', NULL, NULL, NULL, NULL, NULL, NULL, '13', '1', '2020-11-20 10:39:54', '2021-07-01 15:57:11');
INSERT
INTO
    `webconf`
    (`OID`, `KEY`, `DESC`, `TITLE`, `VALUE_TYPE`, `FORM_TYPE`, `TAB_TYPE`, `TAB_TYPE_DESC`, `STRING_VALUE`, `NUM_VALUE`,
     `BOOLEAN_VALUE`, `DATE_VALUE`, `MANDATORY`, `VALIDATE_TYPE`, `VALIDATE_VALUE`, `INDEX`, `VALID`, `CREATE_DATE`,
     `UPDATE_DATE`)
VALUES
    ('18', 'EMAIL_SENDER', '发件人（必须正确，否则发送失败）', '发件人',
     'S', 'INPUT_TEXT', 'EMAIL', '邮件配置',
     '', NULL, NULL, NULL, NULL, NULL, NULL, '13', '1', '2020-11-20 10:39:54', '2021-07-01 15:57:11');
INSERT
INTO
    `webconf`
    (`OID`, `KEY`, `DESC`, `TITLE`, `VALUE_TYPE`, `FORM_TYPE`, `TAB_TYPE`, `TAB_TYPE_DESC`, `STRING_VALUE`, `NUM_VALUE`,
     `BOOLEAN_VALUE`, `DATE_VALUE`, `MANDATORY`, `VALIDATE_TYPE`, `VALIDATE_VALUE`, `INDEX`, `VALID`, `CREATE_DATE`,
     `UPDATE_DATE`)
VALUES
    ('19', 'EMAIL_USER', '用户名（注意：如果使用foxmail邮箱，此处user为qq号）', '用户',
     'S', 'INPUT_TEXT', 'EMAIL', '邮件配置',
     '', NULL, NULL, NULL, NULL, NULL, NULL, '13', '1', '2020-11-20 10:39:54', '2021-07-01 15:57:11');
INSERT
INTO
    `webconf`
    (`OID`, `KEY`, `DESC`, `TITLE`, `VALUE_TYPE`, `FORM_TYPE`, `TAB_TYPE`, `TAB_TYPE_DESC`, `STRING_VALUE`, `NUM_VALUE`,
     `BOOLEAN_VALUE`, `DATE_VALUE`, `MANDATORY`, `VALIDATE_TYPE`, `VALIDATE_VALUE`, `INDEX`, `VALID`, `CREATE_DATE`,
     `UPDATE_DATE`)
VALUES
    ('20', 'EMAIL_PWD', '密码（注意，某些邮箱需要为SMTP服务单独设置密码，详情查看相关帮助）', '密码',
     'S', 'INPUT_TEXT', 'EMAIL', '邮件配置',
     '', NULL, NULL, NULL, NULL, NULL, NULL, '13', '1', '2020-11-20 10:39:54', '2021-07-01 15:57:11');
INSERT
INTO
    `webconf`
    (`OID`, `KEY`, `DESC`, `TITLE`, `VALUE_TYPE`, `FORM_TYPE`, `TAB_TYPE`, `TAB_TYPE_DESC`, `STRING_VALUE`, `NUM_VALUE`,
     `BOOLEAN_VALUE`, `DATE_VALUE`, `MANDATORY`, `VALIDATE_TYPE`, `VALIDATE_VALUE`, `INDEX`, `VALID`, `CREATE_DATE`,
     `UPDATE_DATE`)
VALUES
    ('21', 'EMAIL_STARTTLS', '使用 STARTTLS安全连接，STARTTLS是对纯文本通信协议的扩展。', '开启STARTTLS',
     'B', 'INPUT_CHECKBOX', 'EMAIL', '邮件配置',
     NULL, NULL, '1', NULL, NULL, NULL, NULL, '13', '1', '2020-11-20 10:39:54', '2021-07-01 15:57:11');
INSERT
INTO
    `webconf`
    (`OID`, `KEY`, `DESC`, `TITLE`, `VALUE_TYPE`, `FORM_TYPE`, `TAB_TYPE`, `TAB_TYPE_DESC`, `STRING_VALUE`, `NUM_VALUE`,
     `BOOLEAN_VALUE`, `DATE_VALUE`, `MANDATORY`, `VALIDATE_TYPE`, `VALIDATE_VALUE`, `INDEX`, `VALID`, `CREATE_DATE`,
     `UPDATE_DATE`)
VALUES
    ('22', 'EMAIL_SSL', '使用SSL安全连接', '开启SSL安全连接',
     'B', 'INPUT_CHECKBOX', 'EMAIL', '邮件配置',
     NULL, NULL, '1', NULL, NULL, NULL, NULL, '13', '1', '2020-11-20 10:39:54', '2021-07-01 15:57:11');
INSERT
INTO
    `webconf`
    (`OID`, `KEY`, `DESC`, `TITLE`, `VALUE_TYPE`, `FORM_TYPE`, `TAB_TYPE`, `TAB_TYPE_DESC`, `STRING_VALUE`, `NUM_VALUE`,
     `BOOLEAN_VALUE`, `DATE_VALUE`, `MANDATORY`, `VALIDATE_TYPE`, `VALIDATE_VALUE`, `INDEX`, `VALID`, `CREATE_DATE`,
     `UPDATE_DATE`)
VALUES
    ('23', 'EMAIL_SOCKET_FACTORY_CLASS', '指定实现javax.net.SocketFactory接口的类的名称,这个类将被用于创建SMTP的套接字', 'socketFactoryClass',
     'S', 'INPUT_TEXT', 'EMAIL', '邮件配置',
     '', NULL, NULL, NULL, NULL, NULL, NULL, '13', '1', '2020-11-20 10:39:54', '2021-07-01 15:57:11');
INSERT
INTO
    `webconf`
    (`OID`, `KEY`, `DESC`, `TITLE`, `VALUE_TYPE`, `FORM_TYPE`, `TAB_TYPE`, `TAB_TYPE_DESC`, `STRING_VALUE`, `NUM_VALUE`,
     `BOOLEAN_VALUE`, `DATE_VALUE`, `MANDATORY`, `VALIDATE_TYPE`, `VALIDATE_VALUE`, `INDEX`, `VALID`, `CREATE_DATE`,
     `UPDATE_DATE`)
VALUES
    ('24', 'EMAIL_SOCKET_FACTORY_FALLBACK', '如果设置为true,未能创建一个套接字使用指定的套接字工厂类将导致使用java.net.Socket创建的套接字类, 默认值为true',
     'socketFactoryFallback ',
     'B', 'INPUT_CHECKBOX', 'EMAIL', '邮件配置',
     NULL, NULL, '1', NULL, NULL, NULL, NULL, '13', '1', '2020-11-20 10:39:54', '2021-07-01 15:57:11');
INSERT
INTO
    `webconf`
    (`OID`, `KEY`, `DESC`, `TITLE`, `VALUE_TYPE`, `FORM_TYPE`, `TAB_TYPE`, `TAB_TYPE_DESC`, `STRING_VALUE`, `NUM_VALUE`,
     `BOOLEAN_VALUE`, `DATE_VALUE`, `MANDATORY`, `VALIDATE_TYPE`, `VALIDATE_VALUE`, `INDEX`, `VALID`, `CREATE_DATE`,
     `UPDATE_DATE`)
VALUES
    ('25', 'EMAIL_SOCKET_FACTORY_PORT', '指定的端口连接到在使用指定的套接字工厂。如果没有设置,将使用默认端口456', 'socketFactoryPort ',
     'S', 'INPUT_TEXT', 'EMAIL', '邮件配置',
     '456', NULL, NULL, NULL, NULL, NULL, NULL, '13', '1', '2020-11-20 10:39:54', '2021-07-01 15:57:11');
INSERT
INTO
    `webconf`
    (`OID`, `KEY`, `DESC`, `TITLE`, `VALUE_TYPE`, `FORM_TYPE`, `TAB_TYPE`, `TAB_TYPE_DESC`, `STRING_VALUE`, `NUM_VALUE`,
     `BOOLEAN_VALUE`, `DATE_VALUE`, `MANDATORY`, `VALIDATE_TYPE`, `VALIDATE_VALUE`, `INDEX`, `VALID`, `CREATE_DATE`,
     `UPDATE_DATE`)
VALUES
    ('26', 'EMAIL_STMT_TIMEOUT', 'SMTP超时时长，单位毫秒，缺省值不超时', 'STMT超时时间 ',
     'N', 'INPUT_TEXT', 'EMAIL', '邮件配置',
     NULL, NULL, 0, NULL, NULL, NULL, NULL, '13', '1', '2020-11-20 10:39:54', '2021-07-01 15:57:11');
INSERT
INTO
    `webconf`
    (`OID`, `KEY`, `DESC`, `TITLE`, `VALUE_TYPE`, `FORM_TYPE`, `TAB_TYPE`, `TAB_TYPE_DESC`, `STRING_VALUE`, `NUM_VALUE`,
     `BOOLEAN_VALUE`, `DATE_VALUE`, `MANDATORY`, `VALIDATE_TYPE`, `VALIDATE_VALUE`, `INDEX`, `VALID`, `CREATE_DATE`,
     `UPDATE_DATE`)
VALUES
    ('27', 'EMAIL_SOCKET_TIMEOUT', 'Socket连接超时值，单位毫秒，缺省值不超时', ' Socket超时时间 ',
     'N', 'INPUT_TEXT', 'EMAIL', '邮件配置',
     NULL, NULL, 0, NULL, NULL, NULL, NULL, '13', '1', '2020-11-20 10:39:54', '2021-07-01 15:57:11');


CREATE TABLE `WEBCONF_FACADE`
(
    `OID`            bigint(11) NOT NULL AUTO_INCREMENT COMMENT '表自增唯一id',
    `CONF_OID`       bigint(11) NOT NULL COMMENT 'WEBCONF.OID',
    `DESC`           varchar(200)  DEFAULT NULL,
    `TITLE_DSP`      varchar(50)   DEFAULT NULL,
    `TIPS_DSP`       varchar(50)   DEFAULT NULL,
    `FORM_TYPE`      varchar(20)   DEFAULT NULL COMMENT 'INPUT_TEXT, TEXTAREA; INPUT_FILE_IMAGE; INPUT_TEXT_NUMBER,INPUT_CHECKBOX:,SELECT,RADIO, default:INPUT_TEXT',
    `TAB_TYPE`       varchar(20)   DEFAULT NULL,
    `TAB_TYPE_DSP`   varchar(50)   DEFAULT NULL,
    `MANDATORY`      char(1)       DEFAULT NULL COMMENT '是否必填',
    `VALIDATE_TYPE`  varchar(200)  DEFAULT NULL COMMENT 'maxLength|number|minNum|maxNum|regex... ''|''分隔',
    `VALIDATE_VALUE` varchar(1000) DEFAULT NULL COMMENT 'JSON数据 eg: {\\"maxLength\\":{\\"value\\":50,\\"lay-verify\\":\\"lay-max=''50''\\"}}',
    `INDEX`          int(6)        DEFAULT '1',
    `CREATE_DATE`    datetime   NOT NULL,
    `UPDATE_DATE`    datetime   NOT NULL,
    PRIMARY KEY (`OID`)
) ENGINE = InnoDB
  AUTO_INCREMENT = 28
  DEFAULT CHARSET = utf8 COMMENT ='网站配置表';

INSERT
INTO
    WEBCONF_FACADE(OID, CONF_OID, `DESC`, TITLE_DSP, FORM_TYPE, TAB_TYPE, TAB_TYPE_DSP, MANDATORY, VALIDATE_TYPE,
                   VALIDATE_VALUE, `INDEX`, CREATE_DATE, UPDATE_DATE)
SELECT
    OID, OID, `DESC`, TITLE, FORM_TYPE, TAB_TYPE, TAB_TYPE_DESC, MANDATORY, VALIDATE_TYPE,
    VALIDATE_VALUE, `INDEX`, CREATE_DATE, UPDATE_DATE
FROM
    WEBCONF;


ALTER TABLE `webconf`
    DROP COLUMN TITLE;
ALTER TABLE `webconf`
    DROP COLUMN FORM_TYPE;
ALTER TABLE `webconf`
    DROP COLUMN TAB_TYPE;
ALTER TABLE `webconf`
    DROP COLUMN TAB_TYPE_DESC;
ALTER TABLE `webconf`
    DROP COLUMN MANDATORY;
ALTER TABLE `webconf`
    DROP COLUMN VALIDATE_TYPE;
ALTER TABLE `webconf`
    DROP COLUMN VALIDATE_VALUE;
ALTER TABLE `webconf`
    DROP COLUMN `INDEX`;



CREATE UNIQUE INDEX WEB_CFG_INDEX
    ON `webconf` (`KEY`);



CREATE TABLE `EMAIL`
(
    `OID`            bigint(11)   NOT NULL AUTO_INCREMENT COMMENT '表自增唯一id',
    `TO_EMAIL`       varchar(200) NOT NULL COMMENT '收件人, JSON数组',
    `EMAIL_TPL_CODE` varchar(20)  NOT NULL COMMENT '邮件模板编号',
    `SUBJECT`        varchar(500) NOT NULL COMMENT '邮件主题',
    `CONTENT`        TEXT          DEFAULT NULL COMMENT '邮件内容',
    `JSON_DATA`      varchar(2000) DEFAULT NULL COMMENT '组装的JSON数据',
    `FILES`          varchar(200)  DEFAULT NULL COMMENT '邮件附件',
    `PROC_STATUS`    varchar(10)   DEFAULT '00',
    `PROC_DESC`      varchar(2000) DEFAULT NULL,
    `PROC_TIME`      datetime     NOT NULL,
    `CREATE_DATE`    datetime     NOT NULL,
    `UPDATE_DATE`    datetime     NOT NULL,
    PRIMARY KEY (`OID`)
) ENGINE = InnoDB
  AUTO_INCREMENT = 28
  DEFAULT CHARSET = utf8 COMMENT ='邮箱表';


CREATE UNIQUE INDEX EMAIL_TPL_INDEX
    ON `EMAIL_TEMPLATE` (`EMAIL_TPL_CODE`);

CREATE TABLE `EMAIL_TEMPLATE`
(
    `OID`            bigint(11)   NOT NULL AUTO_INCREMENT COMMENT '表自增唯一id',
    `EMAIL_TPL_CODE` varchar(20)  NOT NULL COMMENT '邮件模板编号',
    `DESC`           varchar(100) NOT NULL COMMENT '描述',
    `SUBJECT`        varchar(500) NOT NULL COMMENT '邮件模板主题',
    `CONTENT`        TEXT         NOT NULL COMMENT '邮件模板内容,HTML格式',
    `TEST_JSON_DATA` varchar(2000) DEFAULT NULL COMMENT '测试的JSON数据',
    `CREATE_DATE`    datetime     NOT NULL,
    `UPDATE_DATE`    datetime     NOT NULL,
    PRIMARY KEY (`OID`)
) ENGINE = InnoDB
  AUTO_INCREMENT = 1
  DEFAULT CHARSET = utf8 COMMENT ='邮件模板';




ALTER TABLE `ARTICLE` MODIFY COLUMN `VISIT_TYPE` VARCHAR(10) DEFAULT '20' COMMENT '公开度[私密:10, 密码:11, 公开:20, 置顶:21]' ;
ALTER TABLE `ARTICLE` MODIFY COLUMN  `STATUS` VARCHAR(10) NOT NULL DEFAULT '00' COMMENT '文章状态 [已发布:90, 草稿:00, 回收站:91,  文章删除状态:99]';
ALTER TABLE `ARTICLE` MODIFY COLUMN  `IS_COMMENT` CHAR(1) NOT NULL DEFAULT '1' COMMENT '是否可以被评论';
ALTER TABLE `ARTICLE` MODIFY COLUMN  `TITLE` VARCHAR(100) NOT NULL COMMENT '文章标题';

ALTER TABLE `ARTICLE` CHANGE COLUMN `PUSH_DATE` `PUSH_TIME` datetime NOT NULL COMMENT '发布时间';
ALTER TABLE `ARTICLE` CHANGE COLUMN `MODIFIED_DATE` `MODIFIED_TIME` datetime NOT NULL COMMENT '修改时间';
ALTER TABLE `ARTICLE` CHANGE COLUMN `DEL_DATE` `DEL_TIME`  datetime DEFAULT NULL COMMENT '删除日期 当状态为99时设置';
ALTER TABLE `ARTICLE` CHANGE COLUMN `CREATE_DATE` `CREATE_TIME`  datetime NOT NULL;
ALTER TABLE `ARTICLE` CHANGE COLUMN `UPDATE_DATE` `UPDATE_TIME`  datetime NOT NULL;
ALTER TABLE `ARTICLE` CHANGE COLUMN `TYPE_ID` `MENU_ID` int(11) DEFAULT '0' COMMENT '文章类型';

ALTER TABLE `TEMP_ARTICLE` CHANGE COLUMN `CREATE_DATE` `CREATE_TIME`  datetime NOT NULL;
ALTER TABLE `TEMP_ARTICLE` CHANGE COLUMN `UPDATE_DATE` `UPDATE_TIME`  datetime NOT NULL;
ALTER TABLE `TEMP_ARTICLE` CHANGE COLUMN `TYPE_ID` `MENU_ID` int(11) DEFAULT '0' COMMENT '文章类型';

ALTER TABLE `TEMP_ARTICLE` MODIFY COLUMN `VISIT_TYPE` VARCHAR(10) DEFAULT '20' COMMENT '公开度[私密:10, 密码:11, 公开:20, 置顶:21]' ;
ALTER TABLE `TEMP_ARTICLE` MODIFY COLUMN `STATUS` VARCHAR(10) NOT NULL DEFAULT '00' COMMENT '文章状态 [已经恢复:90, 临时缓存状态:00, 作废:91]';
ALTER TABLE `TEMP_ARTICLE` MODIFY COLUMN `IS_COMMENT` CHAR(1) DEFAULT NULL DEFAULT '1' COMMENT '是否可以被评论';
ALTER TABLE `TEMP_ARTICLE` CHANGE COLUMN  `PAGE` `PAGE_TYPE` VARCHAR(10) NOT NULL DEFAULT '00' COMMENT '页面类型[10:发布页面 20:编辑页面]';
ALTER TABLE `TEMP_ARTICLE` MODIFY COLUMN  `TITLE` VARCHAR(100) DEFAULT NULL COMMENT '文章标题';
ALTER TABLE `TEMP_ARTICLE` MODIFY COLUMN  `CONTENT`  longtext COMMENT '文章内容(html格式)';

UPDATE `ARTICLE` SET VISIT_TYPE = '20' WHERE VISIT_TYPE = 1;
UPDATE `ARTICLE` SET VISIT_TYPE = '11' WHERE VISIT_TYPE = -1;
UPDATE `ARTICLE` SET VISIT_TYPE = '10' WHERE VISIT_TYPE = 0;
UPDATE `ARTICLE` SET VISIT_TYPE = '21' WHERE VISIT_TYPE = 2;

UPDATE `ARTICLE` SET `STATUS` = '90' WHERE `STATUS` = 1;
UPDATE `ARTICLE` SET `STATUS` = '00' WHERE `STATUS` = 0;
UPDATE `ARTICLE` SET `STATUS` = '91' WHERE `STATUS` = -1;
UPDATE `ARTICLE` SET `STATUS` = '99' WHERE `STATUS` = -2;

UPDATE `TEMP_ARTICLE` SET VISIT_TYPE = '20' WHERE VISIT_TYPE = 1;
UPDATE `TEMP_ARTICLE` SET VISIT_TYPE = '11' WHERE VISIT_TYPE = -1;
UPDATE `TEMP_ARTICLE` SET VISIT_TYPE = '10' WHERE VISIT_TYPE = 0;
UPDATE `TEMP_ARTICLE` SET VISIT_TYPE = '21' WHERE VISIT_TYPE = 2;

UPDATE `TEMP_ARTICLE` SET `STATUS` = '90' WHERE `STATUS` = 1;
UPDATE `TEMP_ARTICLE` SET `STATUS` = '00' WHERE `STATUS` = 0;
UPDATE `TEMP_ARTICLE` SET `STATUS` = '91' WHERE `STATUS` = -1;

UPDATE `TEMP_ARTICLE` SET `PAGE_TYPE` = '10' WHERE `PAGE_TYPE` = 1;
UPDATE `TEMP_ARTICLE` SET `PAGE_TYPE` = '20' WHERE `PAGE_TYPE` = 2;


-- webconf--add int
ALTER TABLE `COMMENTS` CHANGE COLUMN `USER` `USER_NAME` varchar(30) DEFAULT NULL COMMENT '评论用户';
ALTER TABLE `COMMENTS` CHANGE COLUMN `DATE` `COMMENT_TIME` datetime NOT NULL COMMENT '评论日期';
ALTER TABLE `COMMENTS` CHANGE COLUMN `PARENT` `PARENT_OID` bigint(20) NOT NULL COMMENT '父评论OID';
ALTER TABLE `COMMENTS` CHANGE COLUMN `HEAD_IMG` `HEAD_IMG_SRC` varchar(200) DEFAULT NULL COMMENT '头像';
ALTER TABLE `COMMENTS` CHANGE COLUMN `ART_DEL` `ART_DEL_STAUTS` varchar(10) DEFAULT '00' COMMENT '文章删除时为91,未删除为00';
ALTER TABLE `COMMENTS` CHANGE COLUMN `IS_READ` `READ_STATUS` varchar(10) DEFAULT '00' COMMENT '已读状态[00:未读,10:已读]';
ALTER TABLE `COMMENTS` CHANGE COLUMN `CREATE_DATE` `CREATE_TIME`  datetime NOT NULL;
ALTER TABLE `COMMENTS` CHANGE COLUMN `UPDATE_DATE` `UPDATE_TIME`  datetime NOT NULL;

ALTER TABLE `COMMENTS` CHANGE COLUMN `IP` `CLIENT_IP` varchar(10) DEFAULT NULL COMMENT '评论ip';
ALTER TABLE `COMMENTS` CHANGE COLUMN `AREA` `USER_AREA`  varchar(100) DEFAULT NULL COMMENT '用户地区';
ALTER TABLE `COMMENTS` CHANGE COLUMN `QQ` `CONTACT_QQ`  varchar(20) DEFAULT NULL COMMENT '评论者qq';

ALTER TABLE COMMENTS ADD COLUMN `CONTACT_WECHAT` VARCHAR(50) AFTER `CONTACT_QQ` COMMENT '评论者微信';
ALTER TABLE COMMENTS ADD COLUMN `CONTACT_WEIBO` VARCHAR(50) AFTER `CONTACT_WECHAT` COMMENT '评论者微博';
ALTER TABLE COMMENTS ADD COLUMN `CONTACT_TEL` VARCHAR(20) AFTER `CONTACT_WEIBO`  COMMENT '评论者联系手机号';

UPDATE `COMMENTS` SET `ART_DEL_STAUTS` = '91' WHERE `ART_DEL_STAUTS` = 1;
UPDATE `COMMENTS` SET `ART_DEL_STAUTS` = '00' WHERE `ART_DEL_STAUTS` = 0;
UPDATE `COMMENTS` SET `READ_STATUS` = '00' WHERE `READ_STATUS` = 0;
UPDATE `COMMENTS` SET `READ_STATUS` = '10' WHERE `READ_STATUS` = 1;

ALTER TABLE `MENU` MODIFY COLUMN `TYPE` VARCHAR(10) NOT NULL COMMENT '菜单类型[10:前台；20：后台]' ;
ALTER TABLE `MENU` CHANGE COLUMN `CREATE_DATE` `CREATE_TIME`  datetime NOT NULL;
ALTER TABLE `MENU` CHANGE COLUMN `UPDATE_DATE` `UPDATE_TIME`  datetime NOT NULL;

UPDATE `MENU` SET `TYPE` = '10' WHERE `TYPE` = 1;
UPDATE `MENU` SET `TYPE` = '20' WHERE `TYPE` = 2;

ALTER TABLE `ADMIN` CHANGE COLUMN `NICK` `USER_NICK` varchar(50) DEFAULT NULL;
ALTER TABLE `ADMIN` CHANGE COLUMN `PHONE` `USER_PHONE` varchar(20) DEFAULT NULL COMMENT '手机号';
ALTER TABLE `ADMIN` CHANGE COLUMN `EMAIL` `USER_EMAIL`  varchar(20) DEFAULT NULL COMMENT '电子邮件';
ALTER TABLE `ADMIN` CHANGE COLUMN `SEX` `USER_SEX`  varchar(10) DEFAULT NULL COMMENT '性别';
ALTER TABLE `ADMIN` CHANGE COLUMN `IP` `REGISTER_IP`  varchar(20) DEFAULT NULL COMMENT '注册ip地址';
ALTER TABLE `ADMIN` ADD COLUMN `REGISTER_AREA` varchar(30)  DEFAULT NULL  COMMENT '注册地区' AFTER `REGISTER_IP`;
ALTER TABLE `ADMIN` ADD COLUMN `LAST_LOGIN_AREA` varchar(30) DEFAULT NULL  COMMENT '最后登录地区' AFTER `LAST_LOGIN_IP`;
ALTER TABLE `ADMIN` CHANGE COLUMN `CREATE_DATE` `CREATE_TIME`  datetime NOT NULL;
ALTER TABLE `ADMIN` CHANGE COLUMN `UPDATE_DATE` `UPDATE_TIME`  datetime NOT NULL;

ALTER TABLE `ARTICLE_TAGS` CHANGE COLUMN `CREATE_DATE` `CREATE_TIME`  datetime NOT NULL;
ALTER TABLE `ARTICLE_TAGS` CHANGE COLUMN `UPDATE_DATE` `UPDATE_TIME`  datetime NOT NULL;


ALTER TABLE `EMAIL` CHANGE COLUMN `CREATE_DATE` `CREATE_TIME`  datetime NOT NULL;
ALTER TABLE `EMAIL` CHANGE COLUMN `UPDATE_DATE` `UPDATE_TIME`  datetime NOT NULL;

ALTER TABLE `EMAIL_TEMPLATE` CHANGE COLUMN `CREATE_DATE` `CREATE_TIME`  datetime NOT NULL;
ALTER TABLE `EMAIL_TEMPLATE` CHANGE COLUMN `UPDATE_DATE` `UPDATE_TIME`  datetime NOT NULL;

-- BOOLEAN
ALTER TABLE `FILE_UPLOAD` CHANGE COLUMN `CREATE_DATE` `CREATE_TIME`  datetime NOT NULL;
ALTER TABLE `FILE_UPLOAD` CHANGE COLUMN `UPDATE_DATE` `UPDATE_TIME`  datetime NOT NULL;

ALTER TABLE `MODULE` CHANGE COLUMN `CREATE_DATE` `CREATE_TIME`  datetime NOT NULL;
ALTER TABLE `MODULE` CHANGE COLUMN `UPDATE_DATE` `UPDATE_TIME`  datetime NOT NULL;

ALTER TABLE `TAGS` CHANGE COLUMN `CREATE_DATE` `CREATE_TIME`  datetime NOT NULL;
ALTER TABLE `TAGS` CHANGE COLUMN `UPDATE_DATE` `UPDATE_TIME`  datetime NOT NULL;


ALTER TABLE `TYPES` CHANGE COLUMN `CREATE_DATE` `CREATE_TIME`  datetime NOT NULL;
ALTER TABLE `TYPES` CHANGE COLUMN `UPDATE_DATE` `UPDATE_TIME`  datetime NOT NULL;

ALTER TABLE `VISIT` CHANGE COLUMN `IP` `VISIT_IP`  varchar(20) DEFAULT NULL COMMENT '访问ip';
ALTER TABLE `VISIT` CHANGE COLUMN `AREA` `VISIT_AREA`  varchar(100) NOT NULL COMMENT '访问地区';
ALTER TABLE `VISIT` CHANGE COLUMN `VISIT_DATE` `VISIT_TIME`  datetime NOT NULL COMMENT '访问时间';
ALTER TABLE `VISIT` CHANGE COLUMN `CREATE_DATE` `CREATE_TIME`  datetime NOT NULL;
ALTER TABLE `VISIT` CHANGE COLUMN `UPDATE_DATE` `UPDATE_TIME`  datetime NOT NULL;

ALTER TABLE `WEBCONF` ADD COLUMN `INT_VALUE` INT(10) DEFAULT NULL  COMMENT 'INT 类型' AFTER `STRING_VALUE`;
ALTER TABLE `WEBCONF` CHANGE COLUMN `NUM_VALUE` `FLOAT_VALUE`  decimal(10,4) DEFAULT NULL  COMMENT 'FLOAT 类型';
ALTER TABLE `WEBCONF` MODIFY COLUMN `BOOLEAN_VALUE` char(1) DEFAULT NULL COMMENT 'BOOLEAN 类型';
ALTER TABLE `WEBCONF` MODIFY COLUMN `DATE_VALUE` datetime DEFAULT NULL COMMENT 'DATE 类型';
ALTER TABLE `WEBCONF` CHANGE COLUMN `CREATE_DATE` `CREATE_TIME`  datetime NOT NULL;
ALTER TABLE `WEBCONF` CHANGE COLUMN `UPDATE_DATE` `UPDATE_TIME`  datetime NOT NULL;

ALTER TABLE `WEBCONF_FACADE` CHANGE COLUMN `CREATE_DATE` `CREATE_TIME`  datetime NOT NULL;
ALTER TABLE `WEBCONF_FACADE` CHANGE COLUMN `UPDATE_DATE` `UPDATE_TIME`  datetime NOT NULL;
ALTER TABLE `WEBCONF_FACADE` CHANGE COLUMN `MANDATORY` `REQUIRED`   char(1) DEFAULT NULL COMMENT '是否必填';



UPDATE `webconf` SET `OID`='1', `KEY`='TITLE', `DESC`='站点标题', `VALUE_TYPE`='S', `STRING_VALUE`='简窝博客', `INT_VALUE`=NULL, `FLOAT_VALUE`=NULL, `BOOLEAN_VALUE`=NULL, `DATE_VALUE`=NULL, `VALID`='1', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-04-20 14:34:52' WHERE (`OID`='1');
UPDATE `webconf` SET `OID`='2', `KEY`='KEYWORDS', `DESC`='网站关键字', `VALUE_TYPE`='S', `STRING_VALUE`='简窝博客 简窝', `INT_VALUE`=NULL, `FLOAT_VALUE`=NULL, `BOOLEAN_VALUE`=NULL, `DATE_VALUE`=NULL, `VALID`='1', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-04-20 14:34:52' WHERE (`OID`='2');
UPDATE `webconf` SET `OID`='3', `KEY`='DESCRIPTION', `DESC`='网站描述', `VALUE_TYPE`='S', `STRING_VALUE`='简窝博客', `INT_VALUE`=NULL, `FLOAT_VALUE`=NULL, `BOOLEAN_VALUE`=NULL, `DATE_VALUE`=NULL, `VALID`='1', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-04-20 14:34:52' WHERE (`OID`='3');
UPDATE `webconf` SET `OID`='4', `KEY`='RECORD', `DESC`='网站备案', `VALUE_TYPE`='S', `STRING_VALUE`='312341347', `INT_VALUE`=NULL, `FLOAT_VALUE`=NULL, `BOOLEAN_VALUE`=NULL, `DATE_VALUE`=NULL, `VALID`='1', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-04-20 14:34:52' WHERE (`OID`='4');
UPDATE `webconf` SET `OID`='5', `KEY`='AUTHOR', `DESC`='网站作者', `VALUE_TYPE`='S', `STRING_VALUE`='顾', `INT_VALUE`=NULL, `FLOAT_VALUE`=NULL, `BOOLEAN_VALUE`=NULL, `DATE_VALUE`=NULL, `VALID`='1', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-04-20 14:34:52' WHERE (`OID`='5');
UPDATE `webconf` SET `OID`='6', `KEY`='LOGO', `DESC`='上传logo', `VALUE_TYPE`='S', `STRING_VALUE`='http://127.0.0.1:8000//res/13f2b86e016d44ffa49088aa7c12501f_20210420144541053.png', `INT_VALUE`=NULL, `FLOAT_VALUE`=NULL, `BOOLEAN_VALUE`=NULL, `DATE_VALUE`=NULL, `VALID`='1', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-04-20 14:45:50' WHERE (`OID`='6');
UPDATE `webconf` SET `OID`='7', `KEY`='DOMAIN', `DESC`='网站域名', `VALUE_TYPE`='S', `STRING_VALUE`='http://jianwoo.cn', `INT_VALUE`=NULL, `FLOAT_VALUE`=NULL, `BOOLEAN_VALUE`=NULL, `DATE_VALUE`=NULL, `VALID`='1', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-04-20 14:34:52' WHERE (`OID`='7');
UPDATE `webconf` SET `OID`='8', `KEY`='NUM_PER_PAGE', `DESC`='每页显示文章数', `VALUE_TYPE`='I', `STRING_VALUE`=NULL, `INT_VALUE`='12', `FLOAT_VALUE`=NULL, `BOOLEAN_VALUE`=NULL, `DATE_VALUE`=NULL, `VALID`='1', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-08-13 17:13:01' WHERE (`OID`='8');
UPDATE `webconf` SET `OID`='9', `KEY`='IS_COMMENT', `DESC`='开启评论', `VALUE_TYPE`='B', `STRING_VALUE`=NULL, `INT_VALUE`=NULL, `FLOAT_VALUE`=NULL, `BOOLEAN_VALUE`='1', `DATE_VALUE`=NULL, `VALID`='1', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-04-20 14:43:32' WHERE (`OID`='9');
UPDATE `webconf` SET `OID`='10', `KEY`='FOOT_HTML', `DESC`='网站底部信息(支持html)', `VALUE_TYPE`='S', `STRING_VALUE`='adsfasdfadf', `INT_VALUE`=NULL, `FLOAT_VALUE`=NULL, `BOOLEAN_VALUE`=NULL, `DATE_VALUE`=NULL, `VALID`='1', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-04-20 14:34:52' WHERE (`OID`='10');
UPDATE `webconf` SET `OID`='11', `KEY`='TOP_IMG', `DESC`='首页顶部图片:（建议9：1图片）', `VALUE_TYPE`='S', `STRING_VALUE`='http://127.0.0.1:8000//res/d1fe72de39f043d68d7771514d50608f_20210420144548833.jpg', `INT_VALUE`=NULL, `FLOAT_VALUE`=NULL, `BOOLEAN_VALUE`=NULL, `DATE_VALUE`=NULL, `VALID`='1', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-04-20 14:45:50' WHERE (`OID`='11');
UPDATE `webconf` SET `OID`='12', `KEY`='ARTICLE_THUMBNAIL_NUM', `DESC`=NULL, `VALUE_TYPE`='I', `STRING_VALUE`='', `INT_VALUE`=NULL, `FLOAT_VALUE`='500.0000', `BOOLEAN_VALUE`=NULL, `DATE_VALUE`=NULL, `VALID`='0', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2020-11-20 10:39:54' WHERE (`OID`='12');
UPDATE `webconf` SET `OID`='13', `KEY`='IS_LOGIN_NEED_CAPTCHA', `DESC`='登录是否需要验证码', `VALUE_TYPE`='B', `STRING_VALUE`=NULL, `INT_VALUE`=NULL, `FLOAT_VALUE`=NULL, `BOOLEAN_VALUE`='0', `DATE_VALUE`=NULL, `VALID`='1', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-07-01 15:57:11' WHERE (`OID`='13');
UPDATE `webconf` SET `OID`='15', `KEY`='EMAIL_HOST', `DESC`='邮件服务器的SMTP地址', `VALUE_TYPE`='S', `STRING_VALUE`='smtp.mxhichina.com', `INT_VALUE`=NULL, `FLOAT_VALUE`=NULL, `BOOLEAN_VALUE`=NULL, `DATE_VALUE`=NULL, `VALID`='1', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-07-17 17:37:17' WHERE (`OID`='15');
UPDATE `webconf` SET `OID`='16', `KEY`='EMAIL_PORT', `DESC`='邮件服务器的SMTP端口', `VALUE_TYPE`='I', `STRING_VALUE`=NULL, `INT_VALUE`=NULL, `FLOAT_VALUE`='25.0000', `BOOLEAN_VALUE`=NULL, `DATE_VALUE`=NULL, `VALID`='1', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-07-17 23:30:24' WHERE (`OID`='16');
UPDATE `webconf` SET `OID`='18', `KEY`='EMAIL_SENDER', `DESC`='发件人（必须正确，否则发送失败）', `VALUE_TYPE`='S', `STRING_VALUE`='system@jianwoo.cn', `INT_VALUE`=NULL, `FLOAT_VALUE`=NULL, `BOOLEAN_VALUE`=NULL, `DATE_VALUE`=NULL, `VALID`='1', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-07-17 17:37:17' WHERE (`OID`='18');
UPDATE `webconf` SET `OID`='19', `KEY`='EMAIL_USER', `DESC`='用户名（注意：如果使用foxmail邮箱，此处user为qq号）', `VALUE_TYPE`='S', `STRING_VALUE`='system@jianwoo.cn', `INT_VALUE`=NULL, `FLOAT_VALUE`=NULL, `BOOLEAN_VALUE`=NULL, `DATE_VALUE`=NULL, `VALID`='1', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-07-17 17:37:17' WHERE (`OID`='19');
UPDATE `webconf` SET `OID`='20', `KEY`='EMAIL_PWD', `DESC`='密码（注意，某些邮箱需要为SMTP服务单独设置密码，详情查看相关帮助）', `VALUE_TYPE`='S', `STRING_VALUE`='lihua0105...', `INT_VALUE`=NULL, `FLOAT_VALUE`=NULL, `BOOLEAN_VALUE`=NULL, `DATE_VALUE`=NULL, `VALID`='1', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-07-17 17:37:17' WHERE (`OID`='20');
UPDATE `webconf` SET `OID`='21', `KEY`='EMAIL_STARTTLS', `DESC`='使用 STARTTLS安全连接，STARTTLS是对纯文本通信协议的扩展。', `VALUE_TYPE`='B', `STRING_VALUE`=NULL, `INT_VALUE`=NULL, `FLOAT_VALUE`=NULL, `BOOLEAN_VALUE`='0', `DATE_VALUE`=NULL, `VALID`='1', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-07-11 01:32:57' WHERE (`OID`='21');
UPDATE `webconf` SET `OID`='22', `KEY`='EMAIL_SSL', `DESC`='使用SSL安全连接', `VALUE_TYPE`='B', `STRING_VALUE`=NULL, `INT_VALUE`=NULL, `FLOAT_VALUE`=NULL, `BOOLEAN_VALUE`='0', `DATE_VALUE`=NULL, `VALID`='1', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-07-11 01:32:57' WHERE (`OID`='22');
UPDATE `webconf` SET `OID`='23', `KEY`='EMAIL_SOCKET_FACTORY_CLASS', `DESC`='指定实现javax.net.SocketFactory接口的类的名称,这个类将被用于创建SMTP的套接字', `VALUE_TYPE`='S', `STRING_VALUE`=NULL, `INT_VALUE`=NULL, `FLOAT_VALUE`=NULL, `BOOLEAN_VALUE`=NULL, `DATE_VALUE`=NULL, `VALID`='1', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-07-11 18:11:13' WHERE (`OID`='23');
UPDATE `webconf` SET `OID`='24', `KEY`='EMAIL_SOCKET_FACTORY_FALLBACK', `DESC`='如果设置为true,未能创建一个套接字使用指定的套接字工厂类将导致使用java.net.Socket创建的套接字类, 默认值为true', `VALUE_TYPE`='B', `STRING_VALUE`=NULL, `INT_VALUE`=NULL, `FLOAT_VALUE`=NULL, `BOOLEAN_VALUE`='0', `DATE_VALUE`=NULL, `VALID`='1', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-07-11 01:32:57' WHERE (`OID`='24');
UPDATE `webconf` SET `OID`='25', `KEY`='EMAIL_SOCKET_FACTORY_PORT', `DESC`='指定的端口连接到在使用指定的套接字工厂。如果没有设置,将使用默认端口456', `VALUE_TYPE`='I', `STRING_VALUE`=NULL, `INT_VALUE`=NULL, `FLOAT_VALUE`=NULL, `BOOLEAN_VALUE`=NULL, `DATE_VALUE`=NULL, `VALID`='1', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-07-11 18:11:13' WHERE (`OID`='25');
UPDATE `webconf` SET `OID`='26', `KEY`='EMAIL_STMT_TIMEOUT', `DESC`='SMTP超时时长，单位毫秒，缺省值不超时', `VALUE_TYPE`='I', `STRING_VALUE`=NULL, `INT_VALUE`=NULL, `FLOAT_VALUE`=NULL, `BOOLEAN_VALUE`=NULL, `DATE_VALUE`=NULL, `VALID`='1', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-07-11 18:11:13' WHERE (`OID`='26');
UPDATE `webconf` SET `OID`='27', `KEY`='EMAIL_CONNECTION_TIMEOUT', `DESC`='Socket连接超时值，单位毫秒，缺省值不超时', `VALUE_TYPE`='I', `STRING_VALUE`=NULL, `INT_VALUE`=NULL, `FLOAT_VALUE`=NULL, `BOOLEAN_VALUE`=NULL, `DATE_VALUE`=NULL, `VALID`='1', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-07-11 18:11:13' WHERE (`OID`='27');
UPDATE `webconf` SET `OID`='28', `KEY`='EMAIL_TEST_RECEIVER', `DESC`='邮件测试收件人', `VALUE_TYPE`='S', `STRING_VALUE`='1729846470@qq.com', `INT_VALUE`=NULL, `FLOAT_VALUE`=NULL, `BOOLEAN_VALUE`=NULL, `DATE_VALUE`=NULL, `VALID`='1', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-07-17 23:49:57' WHERE (`OID`='28');

UPDATE `webconf_facade` SET `OID`='1', `CONF_OID`='1', `DESC`='站点标题', `TITLE_DSP`='站点标题', `TIPS_DSP`=NULL, `FORM_TYPE`='INPUT_TEXT', `TAB_TYPE`='SYS', `TAB_TYPE_DSP`='系统配置', `REQUIRED`='1', `VALIDATE_TYPE`='maxLength', `VALIDATE_VALUE`='{\"maxLength\":{\"value\":50,\"layVerifyExpress\":\"lay-max=\'50\'\"}}', `INDEX`='1', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-04-20 14:34:52' WHERE (`OID`='1');
UPDATE `webconf_facade` SET `OID`='2', `CONF_OID`='2', `DESC`='网站关键字', `TITLE_DSP`='网站关键字', `TIPS_DSP`=NULL, `FORM_TYPE`='INPUT_TEXT', `TAB_TYPE`='SYS', `TAB_TYPE_DSP`='系统配置', `REQUIRED`=NULL, `VALIDATE_TYPE`='maxLength', `VALIDATE_VALUE`='{\"maxLength\":{\"value\":50,\"layVerifyExpress\":\"lay-max=\'50\'\"}}', `INDEX`='3', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-04-20 14:34:52' WHERE (`OID`='2');
UPDATE `webconf_facade` SET `OID`='3', `CONF_OID`='3', `DESC`='网站描述', `TITLE_DSP`='网站描述', `TIPS_DSP`=NULL, `FORM_TYPE`='TEXTAREA', `TAB_TYPE`='SYS', `TAB_TYPE_DSP`='系统配置', `REQUIRED`=NULL, `VALIDATE_TYPE`='maxLength', `VALIDATE_VALUE`='{\"maxLength\":{\"value\":500,\"layVerifyExpress\":\"lay-max=\'500\'\"}}', `INDEX`='4', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-04-20 14:34:52' WHERE (`OID`='3');
UPDATE `webconf_facade` SET `OID`='4', `CONF_OID`='4', `DESC`='网站备案', `TITLE_DSP`='网站备案', `TIPS_DSP`=NULL, `FORM_TYPE`='INPUT_TEXT', `TAB_TYPE`='SYS', `TAB_TYPE_DSP`='系统配置', `REQUIRED`=NULL, `VALIDATE_TYPE`='maxLength', `VALIDATE_VALUE`='{\"maxLength\":{\"value\":50,\"layVerifyExpress\":\"lay-max=\'50\'\"}}', `INDEX`='5', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-04-20 14:34:52' WHERE (`OID`='4');
UPDATE `webconf_facade` SET `OID`='5', `CONF_OID`='5', `DESC`='网站作者', `TITLE_DSP`='网站作者', `TIPS_DSP`=NULL, `FORM_TYPE`='INPUT_TEXT', `TAB_TYPE`='SYS', `TAB_TYPE_DSP`='系统配置', `REQUIRED`=NULL, `VALIDATE_TYPE`='maxLength', `VALIDATE_VALUE`='{\"maxLength\":{\"value\":20,\"layVerifyExpress\":\"lay-max=\'20\'\"}}', `INDEX`='2', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-04-20 14:34:52' WHERE (`OID`='5');
UPDATE `webconf_facade` SET `OID`='6', `CONF_OID`='6', `DESC`='上传logo', `TITLE_DSP`='上传logo', `TIPS_DSP`=NULL, `FORM_TYPE`='INPUT_FILE_IMAGE', `TAB_TYPE`='SYS', `TAB_TYPE_DSP`='系统配置', `REQUIRED`='1', `VALIDATE_TYPE`='maxLength', `VALIDATE_VALUE`='{\"maxLength\":{\"value\":2000,\"layVerifyExpress\":\"lay-max=\'2000\'\"}}', `INDEX`='8', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-04-20 14:45:50' WHERE (`OID`='6');
UPDATE `webconf_facade` SET `OID`='7', `CONF_OID`='7', `DESC`='网站域名', `TITLE_DSP`='网站域名', `TIPS_DSP`=NULL, `FORM_TYPE`='INPUT_TEXT', `TAB_TYPE`='SYS', `TAB_TYPE_DSP`='系统配置', `REQUIRED`=NULL, `VALIDATE_TYPE`='maxLength', `VALIDATE_VALUE`='{\"maxLength\":{\"value\":50,\"layVerifyExpress\":\"lay-max=\'50\'\"}}', `INDEX`='6', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-04-20 14:34:52' WHERE (`OID`='7');
UPDATE `webconf_facade` SET `OID`='8', `CONF_OID`='8', `DESC`='每页显示文章数', `TITLE_DSP`='每页显示文章数', `TIPS_DSP`=NULL, `FORM_TYPE`='INPUT_TEXT_NUMBER', `TAB_TYPE`='SYS', `TAB_TYPE_DSP`='系统配置', `REQUIRED`=NULL, `VALIDATE_TYPE`='number', `VALIDATE_VALUE`=NULL, `INDEX`='10', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-07-01 15:57:11' WHERE (`OID`='8');
UPDATE `webconf_facade` SET `OID`='9', `CONF_OID`='9', `DESC`='开启评论', `TITLE_DSP`='开启评论', `TIPS_DSP`=NULL, `FORM_TYPE`='INPUT_CHECKBOX', `TAB_TYPE`='SYS', `TAB_TYPE_DSP`='系统配置', `REQUIRED`='', `VALIDATE_TYPE`=NULL, `VALIDATE_VALUE`=NULL, `INDEX`='11', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-04-20 14:43:32' WHERE (`OID`='9');
UPDATE `webconf_facade` SET `OID`='10', `CONF_OID`='10', `DESC`='网站底部信息(支持html)', `TITLE_DSP`='网站底部信息', `TIPS_DSP`='支持html', `FORM_TYPE`='TEXTAREA', `TAB_TYPE`='SYS', `TAB_TYPE_DSP`='系统配置', `REQUIRED`='1', `VALIDATE_TYPE`='maxLength', `VALIDATE_VALUE`='{\"maxLength\":{\"value\":2000 ,\"layVerifyExpress\":\"lay-max=\'2000\'\"}}', `INDEX`='7', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-04-20 14:34:52' WHERE (`OID`='10');
UPDATE `webconf_facade` SET `OID`='11', `CONF_OID`='11', `DESC`='首页顶部图片:（建议9：1图片）', `TITLE_DSP`='首页顶部图片', `TIPS_DSP`='建议9：1图片', `FORM_TYPE`='INPUT_FILE_IMAGE', `TAB_TYPE`='SYS', `TAB_TYPE_DSP`='系统配置', `REQUIRED`=NULL, `VALIDATE_TYPE`='maxLength', `VALIDATE_VALUE`='{\"maxLength\":{\"value\":2000,\"layVerifyExpress\":\"lay-max=\'2000\'\"}}', `INDEX`='9', `CREATE_TIME`='2020-11-20 10:39:00', `UPDATE_TIME`='2021-04-20 14:45:50' WHERE (`OID`='11');
UPDATE `webconf_facade` SET `OID`='12', `CONF_OID`='12', `DESC`=NULL, `TITLE_DSP`=NULL, `TIPS_DSP`=NULL, `FORM_TYPE`='INPUT_TEXT_NUMBER', `TAB_TYPE`='SYS', `TAB_TYPE_DSP`='系统配置', `REQUIRED`=NULL, `VALIDATE_TYPE`=NULL, `VALIDATE_VALUE`=NULL, `INDEX`='13', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2020-11-20 10:39:54' WHERE (`OID`='12');
UPDATE `webconf_facade` SET `OID`='13', `CONF_OID`='13', `DESC`='登录是否需要验证码', `TITLE_DSP`='登录是否需要验证码', `TIPS_DSP`=NULL, `FORM_TYPE`='INPUT_CHECKBOX', `TAB_TYPE`='SYS', `TAB_TYPE_DSP`='系统配置', `REQUIRED`=NULL, `VALIDATE_TYPE`=NULL, `VALIDATE_VALUE`=NULL, `INDEX`='12', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-07-01 15:57:11' WHERE (`OID`='13');
UPDATE `webconf_facade` SET `OID`='15', `CONF_OID`='15', `DESC`='邮件服务器的SMTP地址', `TITLE_DSP`='邮件SMTP地址', `TIPS_DSP`=NULL, `FORM_TYPE`='INPUT_TEXT', `TAB_TYPE`='EMAIL', `TAB_TYPE_DSP`='邮件配置', `REQUIRED`='1', `VALIDATE_TYPE`='maxLength', `VALIDATE_VALUE`='{\"maxLength\":{\"value\":2000,\"layVerifyExpress\":\"lay-max=\'2000\'\"}}', `INDEX`='14', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-07-01 15:57:11' WHERE (`OID`='15');
UPDATE `webconf_facade` SET `OID`='16', `CONF_OID`='16', `DESC`='邮件服务器的SMTP端口', `TITLE_DSP`='邮件SMTP端口', `TIPS_DSP`=NULL, `FORM_TYPE`='INPUT_TEXT_NUMBER', `TAB_TYPE`='EMAIL', `TAB_TYPE_DSP`='邮件配置', `REQUIRED`='1', `VALIDATE_TYPE`='maxLength', `VALIDATE_VALUE`='{\"maxLength\":{\"value\":2000,\"layVerifyExpress\":\"lay-max=\'2000\'\"}}', `INDEX`='15', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-07-01 15:57:11' WHERE (`OID`='16');
UPDATE `webconf_facade` SET `OID`='18', `CONF_OID`='18', `DESC`='发件人（必须正确，否则发送失败）', `TITLE_DSP`='发件人', `TIPS_DSP`=NULL, `FORM_TYPE`='INPUT_TEXT', `TAB_TYPE`='EMAIL', `TAB_TYPE_DSP`='邮件配置', `REQUIRED`='1', `VALIDATE_TYPE`='maxLength', `VALIDATE_VALUE`='{\"maxLength\":{\"value\":2000,\"layVerifyExpress\":\"lay-max=\'2000\'\"}}', `INDEX`='17', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-07-01 15:57:11' WHERE (`OID`='18');
UPDATE `webconf_facade` SET `OID`='19', `CONF_OID`='19', `DESC`='用户名（注意：如果使用foxmail邮箱，此处user为qq号）', `TITLE_DSP`='用户', `TIPS_DSP`=NULL, `FORM_TYPE`='INPUT_TEXT', `TAB_TYPE`='EMAIL', `TAB_TYPE_DSP`='邮件配置', `REQUIRED`='1', `VALIDATE_TYPE`='maxLength', `VALIDATE_VALUE`='{\"maxLength\":{\"value\":2000,\"layVerifyExpress\":\"lay-max=\'2000\'\"}}', `INDEX`='18', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-07-01 15:57:11' WHERE (`OID`='19');
UPDATE `webconf_facade` SET `OID`='20', `CONF_OID`='20', `DESC`='密码（注意，某些邮箱需要为SMTP服务单独设置密码，详情查看相关帮助）', `TITLE_DSP`='密码', `TIPS_DSP`=NULL, `FORM_TYPE`='INPUT_TEXT', `TAB_TYPE`='EMAIL', `TAB_TYPE_DSP`='邮件配置', `REQUIRED`='1', `VALIDATE_TYPE`='maxLength', `VALIDATE_VALUE`='{\"maxLength\":{\"value\":2000,\"layVerifyExpress\":\"lay-max=\'2000\'\"}}', `INDEX`='19', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-07-01 15:57:11' WHERE (`OID`='20');
UPDATE `webconf_facade` SET `OID`='21', `CONF_OID`='21', `DESC`='使用 STARTTLS安全连接，STARTTLS是对纯文本通信协议的扩展。', `TITLE_DSP`='开启STARTTLS', `TIPS_DSP`=NULL, `FORM_TYPE`='INPUT_CHECKBOX', `TAB_TYPE`='EMAIL', `TAB_TYPE_DSP`='邮件配置', `REQUIRED`=NULL, `VALIDATE_TYPE`=NULL, `VALIDATE_VALUE`=NULL, `INDEX`='20', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-07-01 15:57:11' WHERE (`OID`='21');
UPDATE `webconf_facade` SET `OID`='22', `CONF_OID`='22', `DESC`='使用SSL安全连接', `TITLE_DSP`='开启SSL安全连接', `TIPS_DSP`=NULL, `FORM_TYPE`='INPUT_CHECKBOX', `TAB_TYPE`='EMAIL', `TAB_TYPE_DSP`='邮件配置', `REQUIRED`=NULL, `VALIDATE_TYPE`=NULL, `VALIDATE_VALUE`=NULL, `INDEX`='21', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-07-01 15:57:11' WHERE (`OID`='22');
UPDATE `webconf_facade` SET `OID`='23', `CONF_OID`='23', `DESC`='指定实现javax.net.SocketFactory接口的类的名称,这个类将被用于创建SMTP的套接字', `TITLE_DSP`='socket 工厂类', `TIPS_DSP`=NULL, `FORM_TYPE`='INPUT_TEXT', `TAB_TYPE`='EMAIL', `TAB_TYPE_DSP`='邮件配置', `REQUIRED`=NULL, `VALIDATE_TYPE`='maxLength', `VALIDATE_VALUE`='{\"maxLength\":{\"value\":2000,\"layVerifyExpress\":\"lay-max=\'2000\'\"}}', `INDEX`='22', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-07-01 15:57:11' WHERE (`OID`='23');
UPDATE `webconf_facade` SET `OID`='24', `CONF_OID`='24', `DESC`='如果设置为true,未能创建一个套接字使用指定的套接字工厂类将导致使用java.net.Socket创建的套接字类, 默认值为true', `TITLE_DSP`='socket 工厂失败默认', `TIPS_DSP`=NULL, `FORM_TYPE`='INPUT_CHECKBOX', `TAB_TYPE`='EMAIL', `TAB_TYPE_DSP`='邮件配置', `REQUIRED`=NULL, `VALIDATE_TYPE`=NULL, `VALIDATE_VALUE`=NULL, `INDEX`='23', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-07-01 15:57:11' WHERE (`OID`='24');
UPDATE `webconf_facade` SET `OID`='25', `CONF_OID`='25', `DESC`='指定的端口连接到在使用指定的套接字工厂。如果没有设置,将使用默认端口456', `TITLE_DSP`='socket 工厂端口', `TIPS_DSP`=NULL, `FORM_TYPE`='INPUT_TEXT_NUMBER', `TAB_TYPE`='EMAIL', `TAB_TYPE_DSP`='邮件配置', `REQUIRED`=NULL, `VALIDATE_TYPE`=NULL, `VALIDATE_VALUE`=NULL, `INDEX`='24', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-07-01 15:57:11' WHERE (`OID`='25');
UPDATE `webconf_facade` SET `OID`='26', `CONF_OID`='26', `DESC`='SMTP超时时长，单位毫秒，缺省值不超时', `TITLE_DSP`='STMT超时时间 ', `TIPS_DSP`=NULL, `FORM_TYPE`='INPUT_TEXT_NUMBER', `TAB_TYPE`='EMAIL', `TAB_TYPE_DSP`='邮件配置', `REQUIRED`=NULL, `VALIDATE_TYPE`=NULL, `VALIDATE_VALUE`=NULL, `INDEX`='25', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-07-01 15:57:11' WHERE (`OID`='26');
UPDATE `webconf_facade` SET `OID`='27', `CONF_OID`='27', `DESC`='Socket连接超时值，单位毫秒，缺省值不超时', `TITLE_DSP`=' Socket超时时间 ', `TIPS_DSP`=NULL, `FORM_TYPE`='INPUT_TEXT_NUMBER', `TAB_TYPE`='EMAIL', `TAB_TYPE_DSP`='邮件配置', `REQUIRED`=NULL, `VALIDATE_TYPE`=NULL, `VALIDATE_VALUE`=NULL, `INDEX`='26', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2021-07-01 15:57:11' WHERE (`OID`='27');
UPDATE `webconf_facade` SET `OID`='28', `CONF_OID`='28', `DESC`='测试收件人', `TITLE_DSP`='收件人', `TIPS_DSP`=NULL, `FORM_TYPE`='INPUT_TEXT', `TAB_TYPE`='EMAIL', `TAB_TYPE_DSP`='邮件配置', `REQUIRED`=NULL, `VALIDATE_TYPE`='maxLength', `VALIDATE_VALUE`='{\"maxLength\":{\"value\":200,\"layVerifyExpress\":\"lay-max=\'200\'\"}}', `INDEX`='27', `CREATE_TIME`='2020-11-20 10:39:54', `UPDATE_TIME`='2020-11-20 10:39:54' WHERE (`OID`='28');



